### ISSUE TITLE
Please, update to angular 15

### ISSUE THREAD

**Issue by CeloGomesBR** [smartin85/ng-cli-hooks#41]
Need update to angular 15.  Error for "" in angular.json still appears when set new attributes for hooks.

**Comment by christianoerick** [comment]
Same here ☹️

**Comment by smartin85** [comment]
Sorry for this long delay. 
I just published [ng-cli-hooks@15.0.1](https://www.npmjs.com/package/ng-cli-hooks/v/15.0.1) 🎉
Unfortunately I don't have much time to take care of this project, so please contribute when new versions of Angular are released.
As an alternative to this package, you could take a look at the [angular-builders](https://github.com/just-jeb/angular-builders) repo. They are much faster when new Angular versions are released.
